/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Character = IDL.Record({
  'answerPatterns' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : IDL.Text,
  'questionText' : IDL.Text,
  'answerType' : IDL.Text,
});
export const Session = IDL.Record({
  'remainingCandidates' : IDL.Vec(Character),
  'sessionId' : IDL.Text,
  'answersSoFar' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'currentQuestion' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addCharacter' : IDL.Func([Character], [], []),
  'addQuestion' : IDL.Func([Question], [], []),
  'answerQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(Session)],
      [],
    ),
  'getNextQuestion' : IDL.Func([IDL.Text], [IDL.Opt(Question)], ['query']),
  'guessCharacter' : IDL.Func([IDL.Text], [IDL.Opt(Character)], ['query']),
  'startGame' : IDL.Func([IDL.Text], [Session], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Character = IDL.Record({
    'answerPatterns' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : IDL.Text,
    'questionText' : IDL.Text,
    'answerType' : IDL.Text,
  });
  const Session = IDL.Record({
    'remainingCandidates' : IDL.Vec(Character),
    'sessionId' : IDL.Text,
    'answersSoFar' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'currentQuestion' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addCharacter' : IDL.Func([Character], [], []),
    'addQuestion' : IDL.Func([Question], [], []),
    'answerQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(Session)],
        [],
      ),
    'getNextQuestion' : IDL.Func([IDL.Text], [IDL.Opt(Question)], ['query']),
    'guessCharacter' : IDL.Func([IDL.Text], [IDL.Opt(Character)], ['query']),
    'startGame' : IDL.Func([IDL.Text], [Session], []),
  });
};

export const init = ({ IDL }) => { return []; };