/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Character {
  'answerPatterns' : Array<[string, string]>,
  'name' : string,
  'description' : string,
  'category' : string,
}
export interface Question {
  'id' : string,
  'questionText' : string,
  'answerType' : string,
}
export interface Session {
  'remainingCandidates' : Array<Character>,
  'sessionId' : string,
  'answersSoFar' : Array<[string, string]>,
  'currentQuestion' : [] | [string],
}
export interface _SERVICE {
  'addCharacter' : ActorMethod<[Character], undefined>,
  'addQuestion' : ActorMethod<[Question], undefined>,
  'answerQuestion' : ActorMethod<[string, string, string], [] | [Session]>,
  'getNextQuestion' : ActorMethod<[string], [] | [Question]>,
  'guessCharacter' : ActorMethod<[string], [] | [Character]>,
  'startGame' : ActorMethod<[string], Session>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];